### ISSUE TITLE
Fix sliver header scroll behavior

### ISSUE THREAD

**Issue by godon019** [hyochan/BooKoo2#25]
Currently, the header(NestedScrollView's `headerSliverBuilder`) works in a poor way
This should be fixed for better UX

related to #24 

![NaGwwpACwO](https://user-images.githubusercontent.com/27461460/65492330-ac3efa00-deeb-11e9-8975-79c274d4dc99.gif)

**Comment by godon019** [comment]
I will work on it!

**Comment by hyochan** [comment]
Closed via #31

**Comment by godon019** [comment]
Thank you for closing it manually! I forgot using `Fixes #this`
